### ISSUE TITLE
why onProgress will more than 100%?

### ISSUE THREAD

**Issue by yyman001** [englercj/resource-loader#109]
when no load resources, i will not to run `loder.load`, for the one is right , when i load new resources,the `onProgress` will more than `100%->200%`...
   how to do,for every time load new resources is` 0%` to `100%`, about how time to `loder.load`?,no resources to run it, will tips `loader is runing`.
   thanks!!
```js
     load (data) {

      return new Promise((resolve, reject) => {

        let need_load = this.filterCacheForSrc(data)

        console.log('/*****need_load*******/', need_load)
        console.log('loader.resources:', loader.resources)

        // 如果没有队列，loader.load 方法不会执行，所以当没有需要加载的图片的时候，我们直接返回
        if (need_load.length) {
          loader.add(need_load)
        } else {
          console.log(loader);
          resolve(loader.resources)
        }

        //执行加载资源/包括缓存
        if(need_load.length){
          loader.load((loader, resources) => {
            console.log('loader:', loader)
            console.log('/****执行加载资源/包括缓存******/', resources)
          })
        }
        if (!this.initEvent){
          this.initEvent = true
          '/***** 绑定事件******/'
          loader.onProgress.add((v) => {
            console.log('onProgress:', v.progress);
          })

          /*loader.onError.add((v) => {
           console.log('onError:', v);
           })*/

          loader.onComplete.add((v) => {
            console.count('onComplete-progress:', v.progress);

            resolve(loader.resources)
          })
        }


      })

    },
```
the one
![1](https://user-images.githubusercontent.com/5688485/36020837-f9ac6b60-0dbe-11e8-98b1-387466931bdf.png)

new load
![2](https://user-images.githubusercontent.com/5688485/36020846-fec2e944-0dbe-11e8-8bed-2f2e17e37077.png)

**Comment by englercj** [comment]
You can only call `.load()` once per instance. If you want to call it multiple times on a single instance you need to call `.reset()` first.

**Comment by yyman001** [comment]
@englercj the `.reset()` will clear befroe load resources cache. now ,i think use a cache Array save every load resources. I think unreasonable design.
    Thanks your answer.
