### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by daviddelusenet** [englercj/resource-loader#113]
I'm missing all documentation about this loader..

**Comment by themoonrat** [comment]
npm run docs
will generate jsdocs for you

**Comment by daviddelusenet** [comment]
Thanks, works indeed. 

Why don't we add the docs on here tho?

**Comment by englercj** [comment]
The docs can be found here: http://englercj.github.io/resource-loader/

It is listed in the description of the repo on the main page:

![image](https://user-images.githubusercontent.com/944497/37974392-b160e3e4-3191-11e8-8621-cbf616bd5520.png)
