### ISSUE TITLE
Cross origin detection does not work within a sandboxed iframe

### ISSUE THREAD

**Issue by rtibbles** [englercj/resource-loader#119]
When used within a sandboxed iframe, the cross origin auto-detection function does not function properly, as it does not currently check `window.origin` before doing a comparison of the passed in or default location object.

When inside a sandboxed iframe that does not have the `allow-same-origin` attribute (but does have the `allow-scripts` attribute), `window.origin` is set to `null`, whereas `window.location.href` will still return the current URL.

The simplest fix that I would see would be to add a check in the `_determineCrossOrigin` method (https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L890):
```
    _determineCrossOrigin(url, loc) {
        // data: and javascript: urls are considered same-origin
        if (url.indexOf('data:') === 0) {
            return '';
        }

       if (window.origin === null) {
           return 'anonymous';
       }

        // default is window.location
        loc = loc || window.location;

        if (!tempAnchor) {
            tempAnchor = document.createElement('a');
        }

        // let the browser determine the full href for the url of this resource and then
        // parse with the node url lib, we can't use the properties of the anchor element
        // because they don't work in IE9 :(
        tempAnchor.href = url;
        url = parseUri(tempAnchor.href, { strictMode: true });

        const samePort = (!url.port && loc.port === '') || (url.port === loc.port);
        const protocol = url.protocol ? `${url.protocol}:` : '';

        // if cross origin
        if (url.host !== loc.hostname || !samePort || protocol !== loc.protocol) {
            return 'anonymous';
        }

        return '';
    }
```

Let me know if you need more info, or would like me to submit a PR to fix this.

**Comment by englercj** [comment]
Thanks for this @rtibbles, this is certainly a case I haven't tested well. The fix seems reasonable to me, would you mind putting in a PR?

**Comment by rtibbles** [comment]
Great, have submitted a fix! Do you have a sense of when a release might include this change?

**Comment by englercj** [comment]
Right now! https://github.com/englercj/resource-loader/releases/tag/v2.2.0

**Comment by rtibbles** [comment]
Ugh, sorry @englercj, I am afraid I made a mistake in my PR. Chrome and Firefox both set `window.origin` to `'null`' not to `null` inside a sandboxed iframe, I am not sure about other browsers, and I couldn't find a clear specification for what it is always set to.

Will submit another PR shortly that enforces this by doing a `window.origin` versus `window.location.origin` check, which should always work, regardless of what `window.origin` gets set to.

Apologies for the mess up!
