### ISSUE TITLE
InvalidStateError in IE11, line 660 in Resource.js

### ISSUE THREAD

**Issue by ml497** [englercj/resource-loader#125]
Hello,

We've noticed an "InvalidStateError" that has recently started coming up in IE11.  I had a quick look and and it seems like the issue may be similar to this (ie. setting the timeout property of an xhr object before calling open results in this error):
https://github.com/airbrake/airbrake-js/issues/302

Thanks!

**Comment by englercj** [comment]
I moved the timeout, can you see if this works for you?

**Comment by ml497** [comment]
Just tested that and it works :+1:

**Comment by englercj** [comment]
Nice! I'll make a release tonight when I get home.

**Comment by Friksel** [comment]
Just for the record here too: fixed it in IE11 here too. Just glad it's fixed, so now I can switch back to pixi on my project ;)
Thanks for the quick action!

**Comment by englercj** [comment]
v2.2.3 is now released which includes this fix.
