### ISSUE TITLE
Missing mini-signal typing

### ISSUE THREAD

**Issue by milewski** [englercj/resource-loader#127]
Hi the published version to npm is missing the mini-signal declaration:

![image](https://user-images.githubusercontent.com/2874967/55326246-dfaf4780-54b9-11e9-994d-9925ea7d0d30.png)

`resource-loader@2.2.3`

**Comment by englercj** [comment]
There hasn't been a release since they were added:

https://github.com/englercj/resource-loader/commits/master

**Comment by englercj** [comment]
Just published 2.2.4 which should have the goods.
