### ISSUE TITLE
Missing documentation?

### ISSUE THREAD

**Issue by ylambda** [englercj/resource-loader#128]
I was looking to find if a loader stored an object of the loaded resources. I found examples of `Loader.resources` used in the PIXI docs, but couldn't find that member in the resource-loader docs. Digging into the source I found it is commented, but not showing up in the built docs?

[Loader docs](http://englercj.github.io/resource-loader/Loader.html) - No mention of member `resources`
[Loader source](https://github.com/englercj/resource-loader/blob/master/src/Loader.js#L111-L116) - Documented  member `resources`

Maybe that's intentional?

**Comment by englercj** [comment]
Not intentional, looks like none of the Loader and Resource members variables are showing up at all. Not sure what is causing that.

**Comment by englercj** [comment]
I'll be revisiting this when v4 is ready for release as it will significantly change how we setup the API docs.

**Comment by englercj** [comment]
Fixed in v4 rc2
