### ISSUE TITLE
ESM module & TS typings

### ISSUE THREAD

**Issue by bigtimebuddy** [englercj/resource-loader#129]
Because resource-loader does not export an ES module build, it requires users that use Rollup + pixi.js to define named exports. For instance:

**./rollup.config.js**

```js
import commonjs from 'rollup-plugins-commonjs';
export default {
  //...
  plugins: [ 
    commonjs({
      namedExports: { "resource-loader": [ "Resource" ] }
    })
  ]
}
```

It is creating a minor gotcha for users of Rollup and could be alleviated if an ES bundle was created and defined in the **package.json** `module` field.

In addition, TypeScript typings would also help improve developer experience.

**Comment by englercj** [comment]
TypeScript typings are generated here: https://github.com/englercj/resource-loader/tree/master/typings

I'm happy to make any changes that make things easier, but I'm not 100% sure what needs to change. Open to any PRs.
