### ISSUE TITLE
Best way to add new resource types and loading strategies?

### ISSUE THREAD

**Issue by drpepper** [englercj/resource-loader#135]
Hello, I use resource-loader with pixi.js to load images, but I would like to customize the way it loads video and possibly load fonts and audio as well. 

Is there a straightforward way to add in custom loading strategies? The docs describe using middleware for caching or parsing, but perhaps this is where we can do custom loading as well?

Thanks for this great library!

**Comment by englercj** [comment]
Currently there is not a way to inject custom loading strategies. That would be a great refactor to basically replace [this switch](https://github.com/englercj/resource-loader/blob/6d00e3a721a7b6f6befbfe0b61575bf37d309019/src/Resource.js#L446) with a map lookup that can be overriden. Also probably want to change up load type to be more extensible as well.

**Comment by drpepper** [comment]
Great, thanks! I'll come back to this soon.

**Comment by englercj** [comment]
I have an idea how to do this, and I'm implementing v3 in typescript right now and will incorporate this feature.

**Comment by drpepper** [comment]
Awesome! Can't wait to see it.

Le ven. 6 sept. 2019 à 04:48, Chad Engler <notifications@github.com> a
écrit :

**Comment by englercj** [comment]
This feature is added in #137
