### ISSUE TITLE
Adding an array

### ISSUE THREAD

**Issue by brenwell** [englercj/resource-loader#14]
Hey there! I got a simple question. I am moving from pixi.js v2 to v3 and I noticed the change to the your resource loaded. So I was wondering if it was possible to add an array to the loader similar to the version 2 api and if it the name param is required. Currently I am doing the following

```coffeescript
      loader = new PIXI.loaders.Loader()
      for url in urls
        loader.add url,url
      loader.once('complete',callback)
      loader.load()
```

but I would prefer to do something like below

```coffeescript
      loader = new PIXI.loaders.Loader()
      loader.add urls
      loader.once('complete',callback)
      loader.load()
```

Thanks

> Stupid side question, what is the purpose of the `name` parameter?

**Comment by englercj** [comment]
Did you try? Because you can do this right now: #4.

As for the name, it is what the key into the `resources` object will be once things are loaded. instead of using the URL you can pass a human-friendly key to be used instead.

**Comment by englercj** [comment]
Closing since this should work totally fine.

**Comment by brenwell** [comment]
Yes I managed to work with it. Thanks for the help
