### ISSUE TITLE
Pixi resource-loader - add timeout to XHR request

### ISSUE THREAD

**Issue by dranitski** [englercj/resource-loader#144]
Hi all!

Here I have interactive pixijs exmaple that hangs on loading assets and timeouts after a long time https://www.pixiplayground.com/#/edit/pZfY8PQc7PsIJe4ypdavS

Can please anyone help with adding custom **(10s)** timeout to Pixi resource-loader? Any help will be greatly appreciated :)

I was looking through the docs but did not get how to do that or where to pass XHR options. I noticed some Load Strategy interfaced but it is not obvious for me how to use it.

**Comment by eXponenta** [comment]
https://github.com/englercj/resource-loader/blob/8c27956c2ee68e5190e489d87a3e641df035116b/src/Resource.js#L659

loader.add(..., {timeout: 60})
