### ISSUE TITLE
Use resource-loader in a test (jest) context

### ISSUE THREAD

**Issue by Chnapy** [englercj/resource-loader#149]
Hi,

I want to test my app without mocking resource-loader (to see possible regresion on version changes I do not mock my libs). But as jest does not deploy assets, resource-loader finds nothing at http://localhost/*, so all loadings fail.
I see that in your repo you're using karma, which has a `files` config prop which allow to copy desired files. I will not switch to karma, but maybe you know if there is an equivalent on jest config ? Or any workaround that may help me to achieve my goal ?

Thanks.

**Comment by englercj** [comment]
I'm not familiar with Jest at all so I can't help you there.

If you want to mock out the actual loading of a file you can create a LoadStrategy that does nothing but return success with fixture data.

**Comment by Chnapy** [comment]
Ok, if one day I find a solution for jest I'll post it here.
Until then I will do as you say :+1:
