### ISSUE TITLE
Extension is being improperly detected

### ISSUE THREAD

**Issue by dekart** [englercj/resource-loader#17]
We have image URLS like ```http://domain.com/images/abc.png?123456``` where 123456 is an automatically generated timestamp used for cache invalidation. Resource type for such images is being improperly detected when loading which causes issues in a framework (pixi.js) that use your project for resource loading.

Is that possible to exclude everything after ```?``` from extension?

**Comment by englercj** [comment]
Ah, of course. That is totally a bug, I will try to have a fix for it soon. Thanks for bringing it up.

**Comment by FireSlash** [comment]
Ack, I just hit this one as well.

Here's a quick hack for anyone else wedged until an official fix goes out: Change the 'else' case in _getExtension to this
```javascript
			var queryStart = url.indexOf('?');
			if( queryStart !== -1 )
				url = url.substring( 0, queryStart );

			ext = url.substring(url.lastIndexOf('.') + 1);
````
which SHOULD be robust but I didn't spend a lot of time thinking about edge cases.

**Comment by englercj** [comment]
Sorry it took so long, I finally got around to fixing this.
