### ISSUE TITLE
HTML5 Audio object

### ISSUE THREAD

**Issue by fefranca** [englercj/resource-loader#18]
Hi, I just hit an edge case with audio resource loading:

I'm using CocoonJS as a runtime for a game, so `document.createElement("audio")` is not available.

https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L310-L312

This could simply use `new Audio()` as default, falling back to `document.createElement("audio")`, what do you think?

**Comment by englercj** [comment]
I think that makes sense, mind sending a PR?
