### ISSUE TITLE
Feature request : compressed texture

### ISSUE THREAD

**Issue by JiDW** [englercj/resource-loader#20]
Hello !

As you may have see on PIXI github, I'm working on compressed textures for WebGL. We are getting some very nice results in our own engine but dealing wih PIXI and RessourceLoader is a bit too much for me alone.

The thing is PIXI uses an image object for textures. With compressed textures, we need an Int32Array to store the file because an Image() object will not load a .dds or .pvr file.

Could you handle a new type of file (binary file) to be able to load DXT, PVR, ETC and ASTC format please ?

It would require some extra check, fortunatly someone did the homework for us here : https://github.com/toji/texture-tester/blob/master/js/webgl-texture-util.js

As a reminder, compressed texture saves as least 4 times the size of an uncompressed texture in the GPU memory and are faster to bind. This is huge !

Regards.

**Comment by englercj** [comment]
This is already possible without changes to the core lib.

```
var Loader = require('loader'),
    Resource = Loader.Resource,
    loader = new Loader();

loader.add('texture', 'my-texture.dds', { xhrType: Resource.XHR_RESPONSE_TYPE.BUFFER }).load(function(l, res) {
    console.log(new In32Array(res.texture.data)); // data is an ArrayBuffer.
});
```

If you wanted to get fancy and extract data on load, that is what middleware is for. You can also register the texture extension to make them automatically load as array buffer:

```js
Resource.setExtensionLoadType('dds', Resource.LOAD_TYPE.XHR);
Resource.setExtensionXhrType('dds', Resource.XHR_RESPONSE_TYPE.BUFFER);
```

Now all `*.dds` files will be loaded via XHR as array buffers. Now all you need is a parser that will verify if the resource is a compressed texture, and potentially build a data structure for it.

**Comment by JiDW** [comment]
Amazing, sorry for not seeing it myself !

**Comment by englercj** [comment]
No problem, feel free to post an issue if you need help getting the parser setup or have any more questions!
