### ISSUE TITLE
no "complete" after "after"

### ISSUE THREAD

**Issue by thar0x29a** [englercj/resource-loader#21]
Hello dear Sir, 

after setting up some "after" events for middleware the whole loader is not sending any complete event anymore. Not using once, on nor by passing it to the load function itself.

Im not sure if this is wanted that way. But in fact I would love to have a global event that shows up after all of my loading, including my after-progressing is done. Just as it was back then with overloading-extending the old pixi JSONLoader class

**Comment by englercj** [comment]
Sounds like the middleware you are using isn't calling the callbacks properly. Can you post links to the middleware you are using?

**Comment by englercj** [comment]
Closing since there was never any response.
