### ISSUE TITLE
dist folder content crashes text editors

### ISSUE THREAD

**Issue by AndreasDilaveris** [englercj/resource-loader#22]
After running gulp and building out dist folder the resultant .js and .min.js crash my text editors (both sublime and atom) upon attempting to view. 
This happens on every attempt of cloning repo.
This may be an issue with my setup in some way, sorry for the non-code specific issue.  Thought I should mention in case others are experiencing.

**Comment by englercj** [comment]
Nothing to do with this code, everything to do with your editors and/or your machine. You likely have plugins that are trying to do something fancy and choke on minified files.
