### ISSUE TITLE
A test unit related to event progress even middleware add more resources, fail "sometimes"

### ISSUE THREAD

**Issue by jancassio** [englercj/resource-loader#24]
Hi sir @englercj,

I'm playing with the resolution test proof of my pull request I sent to you and I found something strange.

Checkout the log below:

```
not ok 35 Firefox 39.0 - Loader events progress should be 100% on complete, even when a middleware adds more resources
    ---
        message: >
            AssertionError: expected { Object (baseUrl, progress, ...) } to have a property 'progress' of 100, but got 91.81818181818183 (:0)
        stack: >
            process.on/global.onerror@http://localhost:7357/testem/mocha.js:5736:10
            
        Log: >
    ...

```

I'm not able to guess but I'll investigate. Let me know if you have any clue.

Thanks,
Jan

**Comment by englercj** [comment]
Hmm, does this test fail sometimes even without your changes or only with your changes in?

The one thing I wasn't sure about in your PR is how it would effect parsers that add more resources (like a spritesheet parser).

**Comment by jancassio** [comment]
This happen without my changes. I suppose you can reproduce more often if you add a large resource to load at last.

Also, I had not tested only this test, I reproduced this running the entire test suite but I think this doesn't make difference.

**Comment by jancassio** [comment]
Hey @englercj,

I'm working harder this week (probably the next one too) in a short time project, so I'm dedicate few time on this sorry.

Ok today I found something, I got this error all the time the __chunk progress size__ (defined by `_progressChunk` property at `Loader` class), is a float, I know this probably not help so much not but here is a dirty simple log:

```
not ok 35 Firefox 39.0 - Loader events progress should be 100% on complete, even when a middleware adds more resources
    ---
        message: >
            timeout of 2000ms exceeded
        stack: >
            Runnable.prototype.resetTimeout/this.timer<@http://localhost:7357/testem/mocha.js:4254:19
            
        Log: >
            Progress
            66.66666666666667
            num to load
            2
            p chunk
            16.666666666666668
            Progress
            83.33333333333334
            num to load
            1
            p chunk
            16.666666666666668
            Progress
            83.33333333333334
            num to load
            0
            p chunk
            16.666666666666668

```

And here a log of `Loader.enqueue` I guess is the problem starts.

```javascript
if (this._queue.started) {
        this._queue.push(this.resources[name]);
        this._progressChunk = (100 - this.progress) / (this._queue.length() + this._queue.running());
}
````
... and the possible reason for this float result:

```
not ok 35 Firefox 39.0 - Loader events progress should be 100% on complete, even when a middleware adds more resources
    ---
        message: >
            timeout of 2000ms exceeded
        stack: >
            Runnable.prototype.resetTimeout/this.timer<@http://localhost:7357/testem/mocha.js:4254:19
            
        Log: >
            Length: 
            1
            Running: 
            2
            Progress: 
            50
```
I never used this library you are using to create concurrency (async), so need to spend a time reading that documentation before to have a conclusion.

Sorry to say this too late, you made a nice work here (and pixi too, I feel like a Flash Developer making cool things for web again). I'm happy to dive in code.

Thanks for you time.

**Comment by englercj** [comment]
Sounds like just a rounding error then, likely setting progress to a value of `100` just before calling the complete callback is the correct solution.

**Comment by jancassio** [comment]
Seems fair enough, I'll try with more resources with different sizes and check if the test pass with rounding number approach.

Thanks.

**Comment by jancassio** [comment]
Ok, I can't reproduce this problem again in my commit.
In my next push, this problem will be closed.

Thanks,
