### ISSUE TITLE
IE11 Issue with sending cookies in request headers

### ISSUE THREAD

**Issue by vincentg01** [englercj/resource-loader#30]
I am using pixijs version 3.0.2 and facing an unusual error in IE 11. The PNG spritesheets are not loading as pixi loader fails to pass session cookies while making the request to the server for the image (PNG) files. The server denies the request thinking that its an unauthorized access without the session cookies in the request headers. I receive a 403 Forbidden response from the server.  Below is the request header sent to the server by pixi:

Key	Value
Response	HTTP/1.1 403 Forbidden
Server	AkamaiGHost
Mime-Version	1.0
Content-Type	text/html
Content-Length	176
Expires	Mon, 05 Oct 2015 12:59:03 GMT
Cache-Control	max-age=0, no-cache, no-store
Pragma	no-cache
Date	Mon, 05 Oct 2015 12:59:03 GMT
Connection	keep-alive

I also have a normal GIF file used in the IMG src tag; in the same package uploaded to the CMS which loads without errors. Below is the request header sent to the server for this:

Key	Value
Request	GET http://media2-qa.cdiapps.com/repository/protected_content/COMPOUND/50001336/57/16/deploy/media/images/loader.gif HTTP/1.1
Accept	image/png, image/svg+xml, image/*;q=0.8, */*;q=0.5
Referer	http://media2-qa.cdiapps.com/repository/protected_content/COMPOUND/50001336/57/16/deploy/index.html?reviewFlag=false&backUrl=%2Fem4s%2Fgames&context=%7B%22classId%22%3A%22%22%2C+%22gameId%22%3A%22464SB1Q1LNPFDO53FX3RERQTSQ%22%2C+%22bookId%22%3A%22WKFLPQPK563VPDFY6V1FMBXSYE%22%7D&pingUrl=%2Fconnected%2Fkeepalive.form&students=%5B%7B%22studentid%22%3A%22EHC4PHMZYF5CVZ3HT67O1GZSPY%22%2C%22name%22%3A%22Vincent%22%7D%2C%7B%22studentid%22%3A%22student123%22%2C%22name%22%3A%22Brad%22%7D%5D&timeoutInMin=130&connectEDBaseUrl=http%3A%2F%2Fconnected-qa.cdiapps.com%2F&saveServiceJS=%2Fem4t%2FsaveGameEvent.js
Accept-Language	en-US
User-Agent	Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Accept-Encoding	gzip, deflate
Proxy-Connection	Keep-Alive
DNT	1
Host	media2-qa.cdiapps.com
Pragma	no-cache
Cookie	__token__=exp=1444062022~acl=/repository/protected_content/COMPOUND/50001336/57/16/*~hmac=29a424ed54dbf424830a8ece0a95c4dcec23e02b9f4593ec1c9f814f8dea0ee9; PORTALLB=3467057836.55303.0000; JSESSIONID=DFEAA6998C797B5C983CA32D8247083A; _ga=GA1.2.570359160.1443448507

**Comment by englercj** [comment]
Hmm, can you share an example page that reproduces? This seems strange...

**Comment by babumaganti** [comment]
Hi. This is Babu. I don't think we can share the example since its related to environment. We can schedule a meeting and We will be able to show you. Please share your availability.

**Comment by englercj** [comment]
Are you sure both tags point to the same address? I feel like the first one is cross origin or something like that, we use the built-in browser mechanisms for sending these requests so it is in charge of handling whether or not to send cookies.

It is possible we are setting crossorigin incorrectly and preventing cookies.

**Comment by englercj** [comment]
As of 526c9a2d6367e2a31887d4fb4d57c0d791ba648e you can now specify the exact cross origin value to use, including "use-credentials". This should fix your issue since it was caused by using "anonymous".

**Comment by englercj** [comment]
Pixi v3.0.9 includes the changes I made here.
