### ISSUE TITLE
Strategy for loading and decoding audio files

### ISSUE THREAD

**Issue by kittykatattack** [englercj/resource-loader#31]
Dear Sir!

I have question about how best to use the resource loader to load and decode audio files.
Here's the problem I'm trying to solve:

I have arrays of arbitrary file types that I need to load. 
Some of them sometimes contain audio files, something like this:
```
filesToLoad = [
  "image.png",
  "blip.wav",
  "data.json",
  "music.mp3"
];
```
I can load them with the loader like this:
```
    this.loader
      .add(filesToLoad)
      .load(setupFunction);
```
But, I need the audio files to be loaded with an XHR `responseType` of "arraybuffer" and then passed to my local Web Audio API context's `decodeAudioData` method before being added to the loader's resources. 

Is this something the resource loader can do?
Any advice on the strategy I should use to accomplish this would be greatly appreciated :smile: 

PS: Pixi's resource loader is awesome by the way, thanks so much, it's been incredibly fun to use!

**Comment by englercj** [comment]
You can see what the types are that it will try to automatically do for you are:

https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L731-L758

So you have a few options here to make your values load correctly. First if you only want to load a specific resource that way, you can just configure it:

```js
filesToLoad = [
  "image.png",
  { url: "blip.wav", loadType: Resource.LOAD_TYPE.XHR, xhrType: Resource.XHR_RESPONSE_TYPE.BUFFER },
  "data.json",
  "music.mp3"
];
```

That will force that one item to be loaded with XHR as an arraybuffer, but do the default logic for anything else. Alternatively you can register new extensions to be loaded a special way. For example:

```js
// set default loading mechanism for .wav and .mp3 extensions to use XHR
Resource.setExtensionLoadType('wav', Resource.LOAD_TYPE.XHR);
Resource.setExtensionLoadType('mp3', Resource.LOAD_TYPE.XHR);

// set default loading type for .wav and .mp3 extensions to be arraybuffer
Resource.setExtensionXhrType('wav', Resource.XHR_RESPONSE_TYPE.BUFFER);
Resource.setExtensionXhrType('mp3', Resource.XHR_RESPONSE_TYPE.BUFFER);
```

That way any resources to load with the .wav or .mp3 extensions will automatically be detected and loaded properly.

**Comment by kittykatattack** [comment]
Brilliant, thanks so much!
I will run some tests and try these out.

**Comment by kittykatattack** [comment]
I've tested this and the `setExtensionsLoadType` function works!

But, I have another question.
As soon as the audio files have loaded, I need to decode them and get their audio buffers.
Here's the `decodeAudio` function that does this.
It needs a reference to the `xhr.response`, and uses the decoded buffer to make a sound object.
```
function decodeAudio(xhr){
  var decodedBuffer;
  actx.decodeAudioData(
    xhr.response,
    function(buffer) {
      makeSound(buffer);
   },
    function(error) {
      throw new Error("Audio could not be decoded: " + error);
    }
  );
}
```
Is there some way to make the loader run this function as soon as the file has loaded, and also access the loader's XHR object?

**Comment by englercj** [comment]
Closing as this seems solved.
