### ISSUE TITLE
Any consideration using fetch (e.g. polyfill)

### ISSUE THREAD

**Issue by drkibitz** [englercj/resource-loader#33]
Haven't tried this just yet, buts says it support IE9+
https://github.com/github/fetch

**Comment by englercj** [comment]
Interesting idea, I don't have strong motivation to change the XHR logic at this point since it is relatively stable at the moment.

**Comment by lukastaegert** [comment]
An argument against using fetch is the lack of any way to abort running fetch requests; this would be a problem when implementing #49

**Comment by englercj** [comment]
Abort is implemented, and I'm happy with the current implementation for now.
