### ISSUE TITLE
a bug in Loader.prototype._handleBaseUrl

### ISSUE THREAD

**Issue by vitalije** [englercj/resource-loader#35]
Hello I was just studying Loader code and found a bug that is unlikely to show any effect in most practical cases.Nevertheless, I believe it should be fixed. 
```
Loader.prototype._handleBaseUrl = function (url) {
    var parsedUrl = urlParser.parse(url);

    // absolute url, just use it as is.
    if (parsedUrl.protocol || parsedUrl.pathname.indexOf('//') === 0) {
        return url;
    }

    // if baseUrl doesn't end in slash and url doesn't start with slash, then add a slash inbetween
    if (
        this.baseUrl.length &&
        this.baseUrl.lastIndexOf('/') !== this.baseUrl.length - 1 &&
        //HERE INSTEAD
        //  url.lastIndexOf('/') !== url.length - 1
        // SHOULD BE
        url.charAt(0) !== '/'
        // so that this part  of code works like described in the comment above the 'if' statement
    ) {
        return this.baseUrl + '/' + url;
    }
    else {
        return this.baseUrl + url;
    }
};
```

In cases where ```baseUrl``` doesn't end with a slash, and url doesn't begin with a slash, but ends with a slash the original method would return wrong url.
```console.log(new Loader('http://example.org')._handleBaseUrl('wrong/'));```
would produce the following result:
```http://example.orgwrong/```
HTH.

**Comment by englercj** [comment]
Oh shit, good catch. You mind putting in a PR for that?

**Comment by vitalije** [comment]
It is too small change to create PR. It is easier for you to just fix the line. I don't need any credit for that.

**Comment by englercj** [comment]
Its actually much easier to click "merge" than to find the project and edit it, but thanks for pointing this out I will get around to it at some point.

**Comment by vitalije** [comment]
Ok. I have created pull request. I have wrongly supposed that you have this project already in your computer with all necessary libraries installed and that it is easier to you just find and edit one line  of code than it is for me to fork, clone, edit,  download all development libraries, run gulp, commit and finally create pull request. Anyway I guess I was just too lazy to do all that. My bad. It actually didn't take too much time . :blush:
