### ISSUE TITLE
Question about Ressource.error

### ISSUE THREAD

**Issue by JiDW** [englercj/resource-loader#38]
Hello !

I would like to understand how Ressource.error works please. For example here : https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L474

The error is created but not thrown. If it is normal, how does it works ? I'm having trouble to catch these errors in window.onerror

Regards.

**Comment by englercj** [comment]
Correct, but as a user you can check a resource for an error and deal with it. Or the same for any middleware.

The loader will emit an error event for any resources that error during load:

https://github.com/englercj/resource-loader/blob/master/src/Loader.js#L427-L429

**Comment by JiDW** [comment]
Ok thanks ! So something like this would work, right ?

var loader = new PIXI.loaders.Loader();
loader.on('error',function(error){
	throw error;
});

**Comment by englercj** [comment]
if you wanted it to throw, yeah that should be fine.
