### ISSUE TITLE
Forcing XML and JSON to load in plain text.

### ISSUE THREAD

**Issue by josimard** [englercj/resource-loader#40]
Hi,
If we want to use custom parsing for XML and JSON we are now unable to do so...
For example, use the Haxe XML parser or more permissive JSON parsing methods...

I can imagine a <i>text</i> option type when calling ResourceLoader.add():

<code>
.add("xml", "test.xml", {text:true});
</code>

It could be then handled in Resource._xhrOnLoad()

<code>
if (this.xhrType === Resource.XHR_RESPONSE_TYPE.TEXT || options.text===true) { ... 
</code>

**Comment by josimard** [comment]
With jQuery.ajax(), jQuery.get(), etc. the parameter used is "dataType":"text"
http://api.jquery.com/jquery.ajax/

**Comment by englercj** [comment]
You can set the xhrType to text:

```js
.add("xml", "test.xml", { xhrType: Resource.XHR_RESPONSE_TYPE.TEXT });
```

Is that not sufficient?

**Comment by josimard** [comment]
Thanks, that works perfectly!

**Comment by englercj** [comment]
No problem!
