### ISSUE TITLE
'.' in query string breaks extension matching

### ISSUE THREAD

**Issue by eldog** [englercj/resource-loader#45]
`http://example.com/image.png?tag=0.12345` will cause the loader to believe the extension is `12345` not `png` and it will fail to load the image.

Don't know if this deliberate, but caused a problem for me when I was trying to use `Math.random()` as an update flag.

**Comment by eldog** [comment]
Yeah, just made a jsBin for [this](http://jsbin.com/jibare/edit?html,js,output) and it is fixed in the latest version, sorry about that! Was using PIXI 3.0.6, have now upgraded to 3.0.9. 

Closing :)

**Comment by englercj** [comment]
No problem :)
