### ISSUE TITLE
'complete' triggered before 'error'

### ISSUE THREAD

**Issue by pietervanneste** [englercj/resource-loader#46]
Hello,

First of all, thanks for the awesome loader class. I use the loader for multiple file loads in a project and it works great. I just wondering why the 'complete' is first called before the 'error' when the last item of queue fails to load. What's the exact reason for that? Wouldn't it be better if the 'complete' is fired after all items are handled? 

Cheers,
Pieter

**Comment by englercj** [comment]
https://github.com/englercj/resource-loader/blob/master/src/Loader.js#L421-L432

Switching it around probably makes sense.

**Comment by pietervanneste** [comment]
Ok thx :)
