### ISSUE TITLE
Font Loader :D

### ISSUE THREAD

**Issue by GoodBoyDigital** [englercj/resource-loader#5]
https://github.com/GoodBoyDigital/pixi.js/issues/1282

Would be ACE

**Comment by vlucendo** [comment]
I'm using Pixi on a web project and the resource loader is very nice to get also all other necessary stuff.
A font loader or at least a detector would be very cool indeed :)

**Comment by tobireif** [comment]
Also see https://github.com/GoodBoyDigital/pixi.js/issues/1282 .

**Comment by englercj** [comment]
@tobireif That was already linked in the original post O.o, did you mean to link a different issue?

**Comment by kittykatattack** [comment]
Hi Dev Team!
Have you guys just considered forking [Font.js](https://github.com/Pomax/Font.js?MobileOptOut=1) and integrating it into the loader?

**Comment by davidfig** [comment]
I've also had luck with https://github.com/bramstein/fontfaceobserver. Would be great to include that as part of the loader.

**Comment by englercj** [comment]
So I think that the way to go with this is to just load the font files as arraybuffers without parsing them at all. I don't want to recreate all the things necessary in https://github.com/nodebox/opentype.js for parsing, but its trivial to have this load them.

Also sets us up in a good spot to use a library like opentype.js to do SDF text and automatic bitmap fonts. But I have decided that font parsing doesn't belong here, and that binary file loading is as far as I will go with this. Should be easy to add a middleware that uses opentype.js to create a usable font object.
