### ISSUE TITLE
Resource mapping fails for upper case extensions

### ISSUE THREAD

**Issue by mathatan** [englercj/resource-loader#51]
We recently ran into an issue with our files having an upper case extension e.g. `JPG` which wasn't identified correctly as an image. It would probably be beneficial to turn all extensions into lowercase here: https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L776

**Comment by englercj** [comment]
The table is already lowercased, you probably want the extension URL extraction to force lowercase as well:

https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L634

I'd be willing to merge a PR for that.

**Comment by englercj** [comment]
This should be fixed now.
