### ISSUE TITLE
Tracking XHR Bugs when responseType is unsupported.

### ISSUE THREAD

**Issue by englercj** [englercj/resource-loader#6]
Tracking GoodBoyDigital/pixi.js#1557

**Comment by englercj** [comment]
@adireddy Are you experiencing these problems in iOS Safari? If so, which version is that so I can try to reproduce.

**Comment by adireddy** [comment]
Yes iOS 6.1.3 Safari and Chrome.

Looks like It's fine on devices with WebGL (iPad Air 2, iPad mini)

**Comment by englercj** [comment]
This probably has to do with a lack of blob/typedarray support in XHR. I'll see if I can figure out workarounds.

Thanks for the info.

**Comment by adireddy** [comment]
Hey Chad, Just want to quickly check with you if there is any possible solution to fix this as it's rally important for us and I don't want to go back to pixi 2 :)

**Comment by englercj** [comment]
@adireddy I'm sure there are, but I haven't looked yet. I'll probably try to get it done this weekend.

**Comment by adireddy** [comment]
Thanks @englercj.

I have temporarily set 'json' xhr.responseType to 'text/plain' and it works when loading sprite sheets.

Also added a condition checking resource.data.type !== undefined in blob.js to make the loader work temporarily.

**Comment by englercj** [comment]
@adireddy Made a bunch of changes to the lib to try and support these cases.

Here is a special build of pixi that includes the changes I made to resource-loader:

https://dl.dropboxusercontent.com/u/1810371/pixi.js

If you could try that out and let me know if it works for you, I would appreciate it.

**Comment by adireddy** [comment]
Just tested with a bunch of images and the blob issue is definitely fixed now :+1: 

Do let me know if you want to test any other cases.

**Comment by englercj** [comment]
@adireddy Sweet, glad to hear it! I will cut a release then and get these changes into the next pixi RC.

**Comment by adireddy** [comment]
Great. I am assuming that the "json" issue is also fixed. Haven't tested that yet but have seen this in your code :smile: `// *cough* safari *cough* can't deal with it.`

**Comment by englercj** [comment]
:D
