### ISSUE TITLE
Resource loader not able to load files after reset in some cases

### ISSUE THREAD

**Issue by lukastaegert** [englercj/resource-loader#66]
The resource loader is no longer able to load any files if it is reset while there are more than its concurrency limit of files in its queue.

Minimal test case for this issue (I compiled this script with browserify and loaded it inside an HTML file; test1.png to test4.png are just arbitrary files):

```javascript
var Loader = require('resource-loader');
var concurrency = 2;
var loader = new Loader(null, concurrency);

loader.add('test1.png').add('test2.png').add('test3.png').load();

setTimeout(function() {
  loader.reset();
  loader.add('test4.png', finishedLoading).load();
}, 0);

function finishedLoading() {
  console.log('Finished Loading');
}
```

This script loads three files then immediately resets the loader and tries to load a fourth file. When setting `concurrency` to 4 or higher, the last file is loaded correctly and the message 'Finished Loading' appears in the console.
If concurrency is 3 or less, the file is not loaded and the message does not appear.

I tried to debug the problem myself but could not pinpoint the exact issue. If you remove the section in Loader.reset starting with the comment "abort all resource loads" , the problem does no longer occur, but of course this is probably not an ideal solution.

**Comment by englercj** [comment]
Managed to track this down and fix it in v2. Thanks for the repro case, it ended up becoming a test:

https://github.com/englercj/resource-loader/blob/v2/test/unit/Loader.test.js#L272-L286
