### ISSUE TITLE
Reduce File Size

### ISSUE THREAD

**Issue by englercj** [englercj/resource-loader#67]
Async queue and node-url contribute heavily to file size. Try to replace those deps with something more trim.

More details: https://github.com/Fae/fae/issues/22

**Comment by englercj** [comment]
Created the [`slim`](https://github.com/englercj/resource-loader/tree/slim) branch, where I removed `async` completely and replaced `url` with `parse-uri`.

Original File Sizes:
Unminified: **373 KB**
Minified: **63 KB**

New File Sizes:
Unminified: **153 KB**
Minified: **25 KB**

Savings of **60% (39 KB)** on the minified library size.

**Comment by vlucendo** [comment]
Are you planning to merge the slim branch in the future?

**Comment by englercj** [comment]
I am, sorry have been quite busy lately. I'll do it now.

**Comment by englercj** [comment]
Merged and published as v1.8.0!
