### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by staff0rd** [englercj/resource-loader#68]
Previously raised [here](https://github.com/pixijs/pixi.js/issues/2875), I ended up overriding `Resource.load` to allow a cache busting querystring to be attached to all urls processed by the loader, regardless of whether they were added directly, or in-directly via custom parsers.

~~~javascript
var oldLoad = PIXI.loaders.Resource.prototype.load;
PIXI.loaders.Resource.prototype.load = function(cb) {
    this.url += "?v=" + myVersionNumber
    return oldLoad.apply(this, [cb]);
}
~~~

This may be helpful to others using the resource-loader behind a CDN.

**Comment by englercj** [comment]
I wonder if there should be something more generic, allowing people to add any kind of query param to all URLs...

**Comment by englercj** [comment]
What is your ideal way of the loader helping you out with this? I'm working on v2 and could use some insight to what kind of API would work best for your case.

Thanks!

**Comment by englercj** [comment]
Added a new `defaultQueryString` property which will be added to all urls the loader deals with. For your case, you should be able to do this:

```js
loader.defaultQueryString = 'v=' + myVersionNumber;
```

and all your urls will include 'v=' in the querystring.

**Comment by staff0rd** [comment]
Are there breaking changes in this holding up pixijs integration?  I'll give this a go once I can integrate it.

**Comment by englercj** [comment]
There are breaking changes (https://github.com/englercj/resource-loader#upgrading-to-v2).

it is  possible to wrap everything in pixi so it has the same (or very similar) api in PIXI, but I havent gotten around to it yet :(

**Comment by brenwell** [comment]
Oh awesome I have been looking for this feature, for working with spritesheets. Oftern I have no access to the json file so I can version the matching image url.

I had been working on a current solution, but I couldn't workout how to pass on the modified resource. Perhaps someone could point out where I am going wrong.

```typescript
      let loader = new PIXI.loaders.Loader()

      loader.add(urls)

      loader.use(function(resource:any,next:Function){
        if(resource.type === 1){
          resource.data.meta.image += "?versioning!"
        }
        // now return modified resource somehow
        next()
      })
```

Thanks

**Comment by englercj** [comment]
If you use the `defaultQueryString` property I mentioned before the loader should automatically add that query string to all requests it makes.

**Comment by brenwell** [comment]
Terrific. Thanks.
