### ISSUE TITLE
Concurrency limit seems to create a bug with BitmapFont load (pixi)

### ISSUE THREAD

**Issue by JiDW** [englercj/resource-loader#7]
Hello,

First, please note that there is one diff between the master code and the code in the following test case : 
- At line 21872 of pixi.js, we added temp fix for XML parsing

In this test case, the loading never end and stop after 10 files : http://www.celsius-heroes.com/game3/bugLoader.html

In this test case, we modified the concurrency limit to "100" and the loading is sucessfull : 
http://www.celsius-heroes.com/game3/bugLoader2.html

I do believe that it may be linked to adding more ressources to the queue while it is already in a loading state.

Please check the HTML for the source code.

Regards.

**Comment by englercj** [comment]
Hey, thanks for reporting this. I found the issue. The issue is that using `.add()` in a middleware will add something to the queue, but if the queue is already saturated the `next` callback never happens so the queue never drains.

I'm working on the best way to solve this right now.
