### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by bmanderscheid** [englercj/resource-loader#70]
I'm not seeing where I set the scope of the callback function.  How can this be achieved. 
Thank you!

**Comment by englercj** [comment]
[`Function.prototype.bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)?

**Comment by bmanderscheid** [comment]
Thanks for the advice!

I just went with this for now since I'm transpiling.

.load( () => this.assetsLoaded() );
