### ISSUE TITLE
nonsupport gif

### ISSUE THREAD

**Issue by jessjava** [englercj/resource-loader#71]
it's nonsupport the gif type image?

**Comment by englercj** [comment]
Not sure what you are asking, but gif is already set to be leaded via an Image element.

**Comment by jessjava** [comment]
I mean that load a JSON file, the JSON file is not contains a GIF file. yeah? thanks.

**Comment by englercj** [comment]
I have no idea what you are asking. Can you show me an example of what you are trying to do?

**Comment by englercj** [comment]
Closing this, since `gif` images are fully supported by the loader.
