### ISSUE TITLE
Retry when loader emits error

### ISSUE THREAD

**Issue by ddennis** [englercj/resource-loader#73]
Hi - i can't seem to find a way to `retry` when a resource fails to load.
I build an app with pixi and sometimes some of the assets does not load.

```
loader.on('error', function (loadErr , loader, resource){
    resource .load() // was hoping for something like this   
})
```

I can't add the same resource again, causes a `Loader.js:238 Uncaught Error: Resource with name "asda" already exists.`

Is there a recommend way to try a reload?

Any help would be appriciated,

`I am using version 2.0`

/Dennis

**Comment by englercj** [comment]
You can't right now retry a resource while the loader is running. You can however gather the failed resource when the loading finishes and retry them (remember to call `reset()` before using the loader again).

I would like to add an "automatic retry" at some point. But for now, your best bet is to finish and retry all resources that have their `error` property set.

**Comment by ddennis** [comment]
Thanks - it makes sense. [I did example here.](https://jsfiddle.net/cjruh5a9/4/)

It actual seems it has a small bug. When i do the "retry" loading with only the images that fails, the loader complete event is dispatched before the last resource error event.

**Comment by englercj** [comment]
Hmm, error definitely happens before complete:

https://github.com/englercj/resource-loader/blob/master/src/Loader.js#L538

Also, if you are using `loader.on('')` then you are not using v2 of this library. Note that pixi ships with v1.x of this library. I think the bug you mentioned about error coming after complete is fixed in v2 here.

**Comment by ddennis** [comment]
Thank you - i tried to edit the post, as soon as i found i was using an old version.

**Comment by ddennis** [comment]
A question regarding structure?

I am using PIXI v3.0.11 which is using resource loader 1.6.4.

In my project i am using two loaders, one for assets which does not change while the game is playing and another loader handling images that changes several time in a game.

I have basic retry functionality in place, which works. But i would really like to put the responsibility into 
the image container it self and handle each error and retry functionality in the container. 

The "best" solution, i guess, would be to just use new Resource() and handle the loading myself. But then the middleware added by PIXI will not be run.

So my question is this; since it's only 16 images, i thought i could just create a loader for each image,  
[ like in this example ](https://jsfiddle.net/nfmrx0mw/)

Or is there a clever way to added the middleware to each resource manuelly.

**Comment by darting** [comment]
Any update for this feature? Thanks

**Comment by englercj** [comment]
No update, I've been on vacation and now that I am back I am moving. It may be a while before I can circle back to these features.

I am accepting PRs though.

**Comment by englercj** [comment]
I'm going to close this for now, it hasn't been requested very often and some guarantees around data mutability needs to change in order to support it.

If this comes up as a case people need as a core feature we can revisit.
