### ISSUE TITLE
Integration with webpack

### ISSUE THREAD

**Issue by vlucendo** [englercj/resource-loader#77]
Currently using resource-loader with webpack needs a some config adjustments. In package.json `main` points to `./src/index.js` which is written in ES6 so we must add this in webpack.config.js under the babel loader for it to work:

```js
include: [
    //whatever,
    path.resolve(__dirname, 'node_modules/resource-loader')
]
```

Other option would be to change the `main` field of resource-loader to point to `./dist/resource-loader.js` but then webpack says on every compilation:

```
WARNING in ./~/resource-loader/dist/resource-loader.js
Critical dependencies:
1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/resource-loader/dist/resource-loader.js 1:479-486
```

It works but also looks ugly. To hide this we need to add in webpack.config.js:

```js
noParse: [/resource-loader\.js$/]
```

Any ideas about the most elegant way to handle this?

**Comment by englercj** [comment]
We now ship with a `lib/` folder that is the transpiled ES5 code. Feel free to use the `src/` (ES6), `lib/` (ES5), or `dist/` (ES5-combined) files depending on your project's needs.
