### ISSUE TITLE
Usage with cordova + relatives urls (local files)

### ISSUE THREAD

**Issue by Oza94** [englercj/resource-loader#78]
When trying to use pixi.js loader within cordova, it fails with relative urls (e.g. `/foo.png`) because `file://` urls are not allowed in the webview so :
 
```js
PIXI.loader.add('foo', '/foo.png');
```

Fails because on cordova it will try to fetch `file:///foo.png` in the XMLHttpRequest which is disallowed by security settings. The regular way to get local files with cordova seems to be the [FileReader API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader), e.g. for an image : 

```js
var fileReader = new FileReader();
fileReader.onload = function(dataUrl){
  // do something with data url
};
fileReader.onerror = function(){};
fileReader.onprogress = function(){};
fileReader.onabort = function(){};

fileReader.readAsDataURL('/foo.png');
```

However the current `Resource` class is thighly coupled with `XMLHttpRequest` / `Image` ect. Integrate a `FileLoader` option would require a severe refactoring and I'm not confident about doing that myself.

Is there an elegant solution to use pixi.js's loader with cordova ?

**Comment by englercj** [comment]
It would not require severe refactoring, it would require the addition of a "Load Type":

https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L930

Then you add support for it in load:

https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L430

that should be basically it.

**Comment by Oza94** [comment]
Thanks for the feedback :)

My idea was to provide some kind of flag like `useFileReaderAPI=true`, maybe directly at the loader level. With your approach, I should define something like that : 

```js
Resource.LOAD_TYPE = {
    /** Uses XMLHttpRequest to load the resource. */
    XHR:    1,
    /** Uses an `Image` object to load the resource. */
    IMAGE:  2,
    /** Uses an `Audio` object to load the resource. */
    AUDIO:  3,
    /** Uses a `Video` object to load the resource. */
    VIDEO:  4,
    // Use FileReader to load the resource
    FS: 5,
    FS_IMAGE: 6,
    // ...
};
```

But I'm afraid of duplicating code with this approach since some logic like `metadata.skipSource` or `metadata.loadElement` handling is implemented in `_loadElement` or `_loadSource`. Morever, some options like `loadElement` are simply irelevant to the FileReader api context (but I think this is a non-issue).

I'm also not sure about integration the `pixi.js` middlewares that call the loader to fetch additional assets (for instance spritesheet or bitmap font). This is my main use case for this issue : this new option should integrate well and transparently with pixi.js middleware. One example : 

 * I fetch a bitmap font xml file using the loader with a custom load type FS_SOMETHING
 * The bitmapfont parser will try to fetch the texture but... baboum the `LOAD_TYPE.IMAGE` will be used https://github.com/pixijs/pixi.js/blob/dev/src/loaders/bitmapFontParser.js#L126

If you think your approach is the simplest way to go with the above elements let me know and I will start something :)

**Comment by JiDW** [comment]
Hi there,

I may have misundertood but you can load local files from Cordova by using the absolute path, the ressource loader will work fine.

For example, here is how we define the path to our local files downloaded with FileTransfer (on the SD card when possible):

```javascript
var directory = null;
    if(cordova.file.externalDataDirectory === null || config.plateforme.os === "ios")
        directory = cordova.file.dataDirectory;
    else
        directory = cordova.file.externalDataDirectory;
```
This path is readable by RessourceLoader.

**Comment by englercj** [comment]
Updating other middleware to allow an override of the load tpye is an issue for that middleware, not much the loader can do for you there.

As for duplicating logic, just don't duplicate :). After calling `loadAsDataUrl` create a resource that is an image and load it using the data url, once that has completed copy the data over and complete your resource.

```js
fileReader.readAsDataURL('/foo.png');
fileReader.addEventListener('load', function (event) {
    const res = new Resource(event.target.result);
    res.load(function () {
        this.data = res.data;
        this._flags = res._flags;
    });

    // TODO: Error handling
});
```

No duplication required :)

**Comment by englercj** [comment]
v4 adds the ability to have custom loading strategies, so writing a file api load strategy should be trivial after #137 is merged.
