### ISSUE TITLE
Password protected servers

### ISSUE THREAD

**Issue by ayamflow** [englercj/resource-loader#8]
Hi there !
I'm actually using this loader everywhere now that it's "out" of the pixi core, great work here :)

This one is not really a big issue, but maybe it deserves a mention in the readme, or just your opinion on the subjet.

On IE11, loading images from our staging server (which is now protected by a password since we are not launched yet) fails every time, and returns a 401 error. The quickest way I found was to force XHR loading (instead of detected img loading) via the options.

Is there a better/automatic way? Anyway I thought someone using resource-loader might want to know that. Cheers!

**Comment by englercj** [comment]
That is the proper way to use it, if you don't specify a loading mechanism it tries to detect the best one. And loading via <img/> is better than loading via XHR and converting the blob to an <img/> (and more compatible).

You could also just set the username/pass in the baseURL and that should work fine.

**Comment by ayamflow** [comment]
Oh good to kow, thanks!
For now I'm just forcing XHR only on staging server since I'm not sure how XHR works with cache. Anyway thanks for the precision!

**Comment by englercj** [comment]
> since I'm not sure how XHR works with cache. 

Not sure what you mean, both XHR and image requests are going to be chached the exact same way for your case. It would be easier for you have just baseUrl config for each of your environment, and the staging one just includes user/pass. The image should load fine with a url like `http://user:pass@host/`

**Comment by ayamflow** [comment]
Ok, I wasn't sure, now I am :)
