### ISSUE TITLE
There is no texture when suffix is svg

### ISSUE THREAD

**Issue by starInEcust** [englercj/resource-loader#80]
```
loadImages() {
    return new Promise((resolve, reject) => {
      loader
      .add('note0', 'images/renderImages/0.svg')
      .add('note1', 'images/renderImages/1.svg')
      .add('plus', 'images/plus-yellow.png')
      .on('error', reject)
      .load(resolve);
    });
  }
```
note0 and note1 have no texture,but plus has texture.

**Comment by englercj** [comment]
I assume you are referring to a pixi texture, which is created by the textureParser in pixi.

https://github.com/pixijs/pixi.js/blob/dev/src/loaders/textureParser.js

You may want to open this bug there.

**Comment by starInEcust** [comment]
@englercj yes, you are right
I have opened this bug in pixi.js
https://github.com/pixijs/pixi.js/issues/3560
