### ISSUE TITLE
Sound file (.webm, .mp3) loading possible?

### ISSUE THREAD

**Issue by BossLevel** [englercj/resource-loader#81]
As I'm using the loader to load my PIXI graphic resources, I thought it made sense to also load my sound files with it. Unfortunately a) some of these fail (the bigger files) and b) the once 'complete' callback fails to be called roughly 50% of the time (even when the failing files are commented out and no other errors are reported).

I'm happy to provide more info/an example but my first question was whether this was a supported use-case?

FYI I've been using it to load PIXI stuff without issue for months and commenting out the sound asset loading lines results in expected (working) behaviour.

Ta

**Comment by englercj** [comment]
It does support loading audio files in 2 ways:

1) Via an <audio/> element, at which point "complete" is when `canplay` happens.
2) Via XHR, at which point "complete" is when the entire file's data has been downloaded.

Which method are you using, and can you provide a running example that has the failure (or even better a PR that adds a failing test).

**Comment by englercj** [comment]
Closing this since there hasn't been activity for a while.
