### ISSUE TITLE
Load percentage not 100 when complete.

### ISSUE THREAD

**Issue by englercj** [englercj/resource-loader#9]
Tracking GoodBoyDigital/pixi.js#1687

**Comment by englercj** [comment]
@aholla I have added a test case for this, and it seems to work in my tests. Can you give me an example where this isn't working?

**Comment by aholla** [comment]
Sorry having problems loading PIXI into codepen/jsfiddle (it would be good to have an online test bed somewhere).

I was loading one png, one json file that contained just data and another jsonfile that contain atlas data from texturepacker.

**Comment by englercj** [comment]
My test is similar and it seems to work, wonder if you use the latest dev with pixi if it works.

https://github.com/englercj/resource-loader/blob/master/test/unit/Loader.test.js#L276-L337

**Comment by englercj** [comment]
Closing this now since I can't reproduce. Will reopen if more information comes up.
