### ISSUE TITLE
Timeout on XHR requests?

### ISSUE THREAD

**Issue by jcomo** [englercj/resource-loader#90]
In our loading pipeline, we would like to know about timeouts. It looks like the timeout is set for XDR requests but no property is set for XHR requests. Is this intentional?

**Comment by englercj** [comment]
It is not, this is something that should probably be added.

**Comment by jcomo** [comment]
If I could get a PR together for this, what would the timeline be for getting it into a release?

**Comment by englercj** [comment]
As soon as it is merged and tested.
