### ISSUE TITLE
Run after middleware before dequeueing resource

### ISSUE THREAD

**Issue by martindotburke** [englercj/resource-loader#91]
In `Loader.prototype._onLoad ()`, there is a comment specifically stating "run middleware, this *must* happen before dequeue so sub-assets get added properly", yet dequeue is being called before the middleware. 

This seems to be an old bug which was fixed here:

https://github.com/englercj/resource-loader/commit/5fd36a70ccf524413e7ddb8d6764a6e6174ea5dd

And then was re-introduced here:

https://github.com/englercj/resource-loader/commit/f42415bf4eeda605db0d2647e06e10bfa56206cb

I tried moving resource._dequeue around, but that caused the tests to fail. This is currently breaking my after middleware, any help would be much appreciated.

**Comment by englercj** [comment]
`v2.0.8` has been released which should include the fix for this issue.
