### ISSUE TITLE
bug when adding resource during loading 

### ISSUE THREAD

**Issue by mathieuanthoine** [englercj/resource-loader#94]
If I add extra resources with some data in GET after the fileName, the loading operation fail.

Find the attached example.
[loader.zip](https://github.com/englercj/resource-loader/files/1112070/loader.zip)

**Comment by englercj** [comment]
Fixed in v2.0.9

**Comment by mathieuanthoine** [comment]
Stupid question but how the resource-loader is updated in PixiJs, is it automatically added with the current or the next version ? thank you

**Comment by englercj** [comment]
When we make a release, that version is immutable, it will never change. Any changes to pixi will appear in the next version. This will come around in v4.5.4.
