### ISSUE TITLE
sourceScale when loading SVG

### ISSUE THREAD

**Issue by jbjanot** [englercj/resource-loader#95]
Is there any way to have the same parameters than the method FromImage when preloading svg, in particular the sourceScale method? 
Maybe I missed it?

**Comment by englercj** [comment]
I assume you are referring to the [`textureParser`](https://github.com/pixijs/pixi.js/blob/f3da834ccb6ef7fd2470aa4960fa9b79ef0f298a/src/loaders/textureParser.js) middleware in PixiJS?

This lib is generic and is not specific to PixiJS or any library. It doesn't control what parameters are passed into the methods to create textures. It does provide a generic mechanism for passing in whatever "extra data" through the resource you want via the [`metadata`](https://github.com/englercj/resource-loader/blob/d4729e98eac0e9349d3aa49c35fc72893234fd1d/src/Loader.js#L253) parameter. Whatever you pass into that object is stored on the resource and can be used to do whatever you want.

So for example you can check in the texture parser if `resource.metadata.sourceScale` exists, and if so use it somehow. You likely want to open a PR or issue on pixi as this library should already support your use-case.

**Comment by jbjanot** [comment]
Hi @englercj and thank you for your quick answer.
I'm sorry I was not precise enough. I was speaking of the parameter sourceScale in the [BaseTexture class of Pixi](https://github.com/pixijs/pixi.js/blob/f3da834ccb6ef7fd2470aa4960fa9b79ef0f298a/src/core/textures/BaseTexture.js#L672).

I will look into the metadata of the resource, although I'm not sure it will be what I need.

Have a nice day!

**Comment by englercj** [comment]
The metadata lets you pass through anything, so it should be just what you need. You just need to also add support for reading that value in the texture parser.
