### ISSUE TITLE
_loadSourceElement doesn't honor crossOrigin

### ISSUE THREAD

**Issue by englercj** [englercj/resource-loader#99]
Title says it all, this function is not setting the crossOrigin property of the elements it loads.

Workaround: Set `metadata.loadElement` to an Image instance that has the property set as expected.

**Comment by AkashGutha** [comment]
@englercj do we have any update on this?

**Comment by englercj** [comment]
I just haven't had time to put a fix in, a PR would be great.

**Comment by AkashGutha** [comment]
would do for sure if i figure out a fix :)

**Comment by odGit** [comment]
If you are using `new Image()` to load images and now control over server hosting images, then you can add CORS as following:
```
const image = new Image();
image.crossOrigin = "anonymous"; // ask for CORS permission
image.src = 'https://www.somwhere.png';
```
More information can be found here:
[image element Attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Attributes)
[CORS Attributes settings](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes)
